### Access without authentication
GET http://localhost:8081/saloon

### Authenticated access
GET http://localhost:8081/saloon
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwaXN0b2xlcm8iLCJyb2xlIjoic2hvb3RlciJ9.